flyway.url=jdbc:postgresql://host.docker.internal:5432/noharm
flyway.user=postgres
flyway.password=postgres

flyway.locations=filesystem:/flyway/sql
flyway.schemas=public,demo
flyway.baselineOnMigrate=true