flyway.url=jdbc:postgresql://localhost:5432/noharm
flyway.user=postgres
flyway.password=postgres

flyway.schemas=public,demo
flyway.locations=filesystem:./migrations

flyway.connectRetries=10
flyway.baselineOnMigrate=true